<template>
  <view class="page-shell schedule-page">
    <view class="page-head"><view><text class="page-title">日程</text><text class="page-meta">重要的日子，都在这里</text></view><button aria-label="添加重要日" @tap="addReminder">＋</button></view>
    <view class="month-toolbar"><button aria-label="上个月" @tap="changeMonth(-1)">‹</button><text>{{monthTitle}}</text><button aria-label="下个月" @tap="changeMonth(1)">›</button></view>
    <view class="calendar-board">
      <view class="weekday-row"><text v-for="day in weekdays" :key="day">{{day}}</text></view>
      <view class="month-grid"><view v-for="cell in calendarCells" :key="cell.key" class="day-cell" :class="{today:cell.isToday,selected:cell.key===selectedDateKey,empty:!cell.day,rest:cell.holiday?.status==='rest',work:cell.holiday?.status==='work'}" @tap="cell.day&&selectDate(cell.key)"><view v-if="cell.day" class="day-number"><text>{{cell.day}}</text><text v-if="cell.holiday?.status" class="day-status">{{cell.holiday.status==='rest'?'休':'班'}}</text></view><text v-if="cell.holiday?.name" class="holiday-name">{{cell.holiday.name}}</text><view v-if="cell.eventCount" class="dots"><text v-for="dot in Math.min(cell.eventCount,3)" :key="dot"></text></view></view></view>
    </view>

    <view class="agenda-section">
      <view class="agenda-head"><view><text>{{agendaTitle}}</text><text>{{agendaItems.length?`${agendaItems.length} 件安排`:'没有安排'}}</text></view><text @tap="toggleAll">{{selectedDateKey?'查看全部':'回到今天'}}</text></view>
      <view v-if="loading" class="loading-list"><view v-for="item in 3" :key="item"></view></view>
      <view v-else-if="agendaItems.length" class="agenda-list">
        <view v-for="item in agendaItems" :key="reminderKey(item)" class="agenda-row">
          <view class="date-column"><text>{{dateLabel(item.eventDate)}}</text><text>{{formatWeekDate(item.eventDate)}}</text></view>
          <view class="agenda-content" @tap="goEvent(item)"><view class="person-avatar">{{personName(item).slice(0,1)}}</view><view class="agenda-copy"><text>{{item.eventTitle}}</text><text>{{personName(item)}} · {{formatWeekDate(item.eventDate)}}</text></view><view class="agenda-days"><text>{{eventDays(item)===0?'今天':`${eventDays(item)}天后`}}</text><text>›</text></view></view>
          <button @tap="prepareFor(item)">✦ 准备</button>
        </view>
      </view>
      <view v-else class="empty-agenda"><view><text>{{selectedDateLabel}}</text><text>{{selectedHoliday?.name||formatWeekDate(selectedDate)}}</text></view><text>这一天没有安排</text><button @tap="addReminder">添加重要日</button></view>
    </view>
    <BottomNav v-if="store.isLogin" active="reminders" :reminder-count="todayReminders.length" />
  </view>
</template>

<script setup>
import{computed,ref}from'vue';import{onHide,onLoad,onShow,onUnload}from'@dcloudio/uni-app';import BottomNav from '@/components/BottomNav.vue';import{store}from'@/store/index.js';import{eventApi}from'@/api/event.js';import{relationshipApi}from'@/api/relationship.js';import{openContactCreationMenu}from'@/utils/contactCreation.js';
import{getChinaHoliday}from'@/utils/chinaHoliday.js';
const now=new Date(),calendarMonth=ref(new Date(now.getFullYear(),now.getMonth(),1)),selectedDateKey=ref(toDateKey(now)),todayReminders=ref([]),upcomingReminders=ref([]),relationships=ref([]),loading=ref(false);const weekdays=['一','二','三','四','五','六','日'];
const reminderKey=item=>`${item.sourceType||'RELATIONSHIP'}:${item.eventId||item.sharedEventId}:${item.eventDate}`;const allReminders=computed(()=>{const map=new Map();for(const item of[...todayReminders.value,...upcomingReminders.value])if(!map.has(reminderKey(item)))map.set(reminderKey(item),item);return[...map.values()].sort((a,b)=>new Date(a.eventDate)-new Date(b.eventDate));});const monthTitle=computed(()=>`${calendarMonth.value.getFullYear()}年 ${calendarMonth.value.getMonth()+1}月`);
const calendarCells=computed(()=>{const year=calendarMonth.value.getFullYear(),month=calendarMonth.value.getMonth(),leading=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),cells=Array.from({length:leading},(_,index)=>({key:`start-${index}`,day:0,eventCount:0}));for(let day=1;day<=days;day++){const date=new Date(year,month,day),key=toDateKey(date);cells.push({key,day,isToday:key===toDateKey(now),holiday:getChinaHoliday(key),eventCount:allReminders.value.filter(item=>toDateKey(new Date(item.eventDate))===key).length});}while(cells.length%7)cells.push({key:`end-${cells.length}`,day:0,eventCount:0});return cells;});
const agendaItems=computed(()=>selectedDateKey.value?allReminders.value.filter(item=>toDateKey(new Date(item.eventDate))===selectedDateKey.value):allReminders.value);const selectedDate=computed(()=>selectedDateKey.value?fromDateKey(selectedDateKey.value):now);const selectedHoliday=computed(()=>selectedDateKey.value?getChinaHoliday(selectedDateKey.value):null);const agendaTitle=computed(()=>{if(!selectedDateKey.value)return'未来 90 天';const prefix=selectedDateKey.value===toDateKey(now)?'今天':dateLabel(selectedDate.value);const holiday=selectedHoliday.value?.name?` · ${selectedHoliday.value.name}`:'';return`${prefix} ${formatWeekDate(selectedDate.value)}${holiday}`;});const selectedDateLabel=computed(()=>dateLabel(selectedDate.value));
let loadGeneration=0;const cancelPendingLoad=()=>{loadGeneration+=1;};onHide(cancelPendingLoad);onUnload(cancelPendingLoad);
onLoad(options=>{if(options?.date){const date=fromDateKey(options.date);if(!Number.isNaN(date.getTime())){selectedDateKey.value=options.date;calendarMonth.value=new Date(date.getFullYear(),date.getMonth(),1);}}});onShow(()=>{if(!store.isLogin){uni.reLaunch({url:'/pages/login/login'});return;}load();});
const load=async()=>{const generation=++loadGeneration;loading.value=true;try{const[occurrences,people]=await Promise.all([eventApi.upcoming(90),relationshipApi.list(store.userId)]);if(generation!==loadGeneration)return;upcomingReminders.value=occurrences||[];todayReminders.value=(occurrences||[]).filter(item=>eventDays(item)===0);relationships.value=people||[];}finally{if(generation===loadGeneration)loading.value=false;}};
function toDateKey(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}function fromDateKey(key){const[year,month,day]=String(key).split('-').map(Number);return new Date(year,month-1,day);}
const eventDays=item=>{if(item?.daysUntilEvent!==null&&item?.daysUntilEvent!==undefined&&Number.isFinite(Number(item.daysUntilEvent)))return Math.max(0,Number(item.daysUntilEvent));const target=new Date(item?.eventDate),today=new Date();target.setHours(0,0,0,0);today.setHours(0,0,0,0);return Number.isNaN(target.getTime())?0:Math.max(0,Math.round((target-today)/86400000));};const personName=item=>item.relationshipName||(item.sourceType==='SPACE'?'共同空间':'重要的人');const dateLabel=value=>{const date=value instanceof Date?value:new Date(value);return`${date.getMonth()+1}月${date.getDate()}日`;};const formatWeekDate=value=>['周日','周一','周二','周三','周四','周五','周六'][(value instanceof Date?value:new Date(value)).getDay()];
const selectDate=key=>{selectedDateKey.value=key;};const changeMonth=offset=>{calendarMonth.value=new Date(calendarMonth.value.getFullYear(),calendarMonth.value.getMonth()+offset,1);selectedDateKey.value='';};const toggleAll=()=>{if(selectedDateKey.value)selectedDateKey.value='';else{calendarMonth.value=new Date(now.getFullYear(),now.getMonth(),1);selectedDateKey.value=toDateKey(now);}};
const addReminder=()=>{if(!relationships.value.length)return openContactCreationMenu();uni.showActionSheet({itemList:relationships.value.map(item=>item.name),success:({tapIndex})=>uni.navigateTo({url:`/pages/event/create?relationshipId=${relationships.value[tapIndex].id}`})});};const prepareFor=item=>uni.showActionSheet({itemList:['写一句祝福','获取礼物建议'],success:({tapIndex})=>uni.navigateTo({url:`/pages/ai/${tapIndex===0?'blessing':'gift'}?relationshipId=${item.relationshipId||''}`})});const goEvent=item=>uni.navigateTo({url:item.sourceType==='SPACE'?`/pages/space/detail?id=${item.sharedSpaceId}`:`/pages/relationship/detail?id=${item.relationshipId}`});
</script>

<style scoped>
.schedule-page{padding-top:24rpx}.page-head,.month-toolbar,.weekday-row,.agenda-head,.agenda-row,.agenda-content{display:flex;align-items:center}.page-head,.agenda-head{justify-content:space-between}.page-head>view{display:flex;flex-direction:column}.page-meta{margin-top:4rpx;color:#858c87;font-size:28rpx}.page-head button{width:80rpx;height:80rpx;margin:0;padding:0;border-radius:50%;background:#315c4d;color:#fff;line-height:78rpx;font-size:36rpx}.month-toolbar{margin-top:28rpx;justify-content:space-between}.month-toolbar text{font-size:34rpx;font-weight:700}.month-toolbar button{width:76rpx;height:76rpx;margin:0;padding:0;border-radius:50%;background:transparent;color:#68706b;line-height:74rpx;font-family:Georgia,serif;font-size:44rpx}
.calendar-board{margin-top:12rpx;padding:14rpx 4rpx 12rpx;border-top:1rpx solid #dfe2dd;border-bottom:1rpx solid #dfe2dd}.weekday-row text{flex:1;text-align:center;color:#969c98;font-size:26rpx}.month-grid{margin-top:8rpx;display:grid;grid-template-columns:repeat(7,1fr);grid-auto-rows:112rpx}.day-cell{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:flex-start;padding-top:7rpx}.day-number{position:relative;width:60rpx;height:60rpx;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#3d4540;font-size:30rpx}.day-cell.today .day-number{border:1rpx solid #315c4d;color:#315c4d;font-weight:700}.day-cell.selected .day-number{border-color:#315c4d;background:#315c4d;color:#fff}.day-status{position:absolute;top:-8rpx;right:-14rpx;min-width:30rpx;height:30rpx;padding:0 4rpx;border-radius:6rpx;display:flex;align-items:center;justify-content:center;background:#f2dfda;color:#a95648;font-size:26rpx;line-height:30rpx;font-weight:700}.day-cell.work .day-status{background:#f1e7d4;color:#7a612d}.holiday-name{position:absolute;left:0;right:0;bottom:0;display:block;color:#a95648;font-size:26rpx;line-height:30rpx;text-align:center;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.day-cell.work .holiday-name{color:#7a612d}.dots{position:absolute;top:10rpx;left:7rpx;display:flex;gap:3rpx}.dots text{width:6rpx;height:6rpx;border-radius:50%;background:#c76755}.day-cell.selected .dots text{background:#d9bb75}
.agenda-section{margin-top:28rpx}.agenda-head>view{flex:1;min-width:0;display:flex;flex-direction:column}.agenda-head>view text:first-child{font-size:34rpx;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agenda-head>view text:last-child{margin-top:4rpx;color:#8b918d;font-size:28rpx}.agenda-head>text{flex:none;padding:12rpx 0 12rpx 20rpx;color:#315c4d;font-size:28rpx;white-space:nowrap}.agenda-list{margin-top:10rpx}.agenda-row{position:relative;min-height:148rpx;border-bottom:1rpx solid #e1e4df}.date-column{width:108rpx;flex:none;display:flex;flex-direction:column;align-items:flex-start}.date-column text:first-child{font-size:30rpx;font-weight:700;white-space:nowrap}.date-column text:last-child{margin-top:4rpx;color:#929894;font-size:26rpx}.agenda-content{flex:1;min-width:0;padding:20rpx 0}.person-avatar{width:76rpx;height:76rpx;margin-right:15rpx;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#e1e9e4;color:#3e6658;font-size:30rpx;font-weight:700;flex:none}.agenda-copy{flex:1;min-width:0;display:flex;flex-direction:column}.agenda-copy text:first-child{font-size:32rpx;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agenda-copy text:last-child{margin-top:5rpx;color:#8b918d;font-size:28rpx}.agenda-days{width:88rpx;display:flex;align-items:center;justify-content:flex-end;gap:6rpx}.agenda-days text:first-child{color:#a95648;font-size:28rpx;font-weight:650}.agenda-days text:last-child{color:#9ca29e;font-size:34rpx}.agenda-row>button{position:absolute;right:0;bottom:4rpx;height:64rpx;margin:0;padding:0 16rpx;border-radius:7rpx;background:#f1e7d4;color:#7a612d;line-height:64rpx;font-size:26rpx}.loading-list{margin-top:16rpx}.loading-list view{height:140rpx;border-bottom:1rpx solid #e1e4df;background:linear-gradient(90deg,transparent,#ecefeb,transparent);background-size:200% 100%}.empty-agenda{min-height:330rpx;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#89908c}.empty-agenda>view{width:150rpx;height:96rpx;margin-bottom:18rpx;border-radius:9rpx;display:flex;flex-direction:column;align-items:center;justify-content:center;background:#e4ece7;color:#315c4d}.empty-agenda>view text:first-child{font-size:30rpx;font-weight:700;white-space:nowrap}.empty-agenda>view text:last-child{margin-top:3rpx;font-size:26rpx}.empty-agenda>text{color:#35403a;font-size:32rpx;font-weight:650}.empty-agenda button{height:88rpx;margin-top:20rpx;padding:0 28rpx;border-radius:9rpx;background:#315c4d;color:#fff;line-height:88rpx;font-size:30rpx}
</style>
