<template>
  <button class="back-button" aria-label="Back" @tap="goBack">‹</button>
  <view class="memory-detail-page">
    <view v-if="memory" class="memory-content"><view class="detail-head"><view><text class="eyebrow">MEMORY</text><text class="page-title">记录详情</text><text class="detail-subtitle">{{ formatDate(memory.memoryDate || memory.createdAt) }} · {{ relationshipName }}</text></view><button class="edit-button" @tap="edit">编辑</button></view><view v-if="memory.imageUrl" class="memory-image-wrap"><image :src="memory.imageUrl" mode="aspectFill" /></view><view v-else class="memory-art"><text>{{ (memory.content || '记录').slice(0, 10) }}</text></view><view class="memory-copy"><text class="memory-title">{{ memory.content || '未命名记录' }}</text><text v-if="memory.content" class="memory-body">{{ memory.content }}</text></view><view class="detail-section"><view class="section-head"><text>相关信息</text></view><view class="info-row"><text>关联人物</text><strong>{{ relationshipName }}</strong></view><view class="info-row"><text>记录时间</text><strong>{{ formatDate(memory.memoryDate || memory.createdAt) }}</strong></view><view class="info-row"><text>所属空间</text><strong>我的记录</strong></view></view><view class="detail-actions"><button class="primary-button" @tap="share">分享回忆</button><button class="quiet-button" @tap="remove">删除记录</button></view></view><view v-else class="loading-state"><text>{{ error || '正在加载记录…' }}</text><button v-if="error" @tap="load">重试</button></view>
  </view>
</template>

<script setup>
import { ref } from 'vue';
import { onLoad, onShow } from '@dcloudio/uni-app';
import { memoryApi } from '@/api/memory.js';
import { relationshipApi } from '@/api/relationship.js';
import { store } from '@/store/index.js';

const memoryId = ref(0); const relationshipId = ref(0); const memory = ref(null); const relationshipName = ref('重要的人'); const error = ref('');
onLoad((options) => { memoryId.value = Number(options?.id) || 0; relationshipId.value = Number(options?.relationshipId) || 0; }); onShow(() => { if (!store.isLogin) return uni.reLaunch({ url: '/pages/login/login' }); if (memoryId.value) load(); });
const load = async () => { error.value = ''; try { memory.value = await memoryApi.detail(memoryId.value); relationshipId.value = memory.value.relationshipId || relationshipId.value; if (relationshipId.value) { const person = await relationshipApi.detail(relationshipId.value); relationshipName.value = person?.name || relationshipName.value; } } catch (requestError) { error.value = requestError?.message || '记录加载失败'; } };
const formatDate = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : `${date.getFullYear()}年${date.getMonth() + 1}月${date.getDate()}日`; }; const edit = () => uni.navigateTo({ url: `/pages/memory/create?id=${memoryId.value}&relationshipId=${relationshipId.value}` }); const share = () => uni.showToast({ title: '分享功能即将开放', icon: 'none' }); const remove = () => uni.showModal({ title: '删除记录', content: '删除后将无法恢复，确认继续吗？', confirmColor: '#b64f43', success: async ({ confirm }) => { if (!confirm) return; await memoryApi.remove(memoryId.value); uni.showToast({ title: '已删除', icon: 'success' }); setTimeout(() => uni.navigateBack(), 500); } });
const goBack = () => { const pages = getCurrentPages(); if (pages.length > 1) return uni.navigateBack(); uni.reLaunch({ url: '/pages/memory/list' }); };
</script>

<style scoped>
.memory-detail-page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f7f7f5}.detail-head{display:flex;align-items:flex-start;justify-content:space-between}.detail-head>view{display:flex;flex-direction:column}.eyebrow{color:#9a6d54;font-size:24rpx;font-weight:700;letter-spacing:2rpx}.detail-subtitle{margin-top:8rpx;color:#858c87;font-size:28rpx}.edit-button{height:64rpx;margin:12rpx 0 0 12rpx;padding:0 18rpx;border:1rpx solid #dfe2dd;border-radius:9rpx;background:#fff;color:#315c4d;line-height:62rpx;font-size:27rpx}.memory-image-wrap,.memory-art{margin-top:26rpx;overflow:hidden;border-radius:9rpx}.memory-image-wrap{height:440rpx;background:#e9ece8}.memory-image-wrap image{width:100%;height:100%}.memory-art{height:440rpx;padding:26rpx;display:flex;align-items:flex-end;background:#f1e7d4;color:#7a612d;font-family:Georgia,serif;font-size:48rpx}.memory-copy{margin-top:22rpx}.memory-title{display:block;font-size:36rpx;font-weight:700}.memory-body{display:block;margin-top:12rpx;color:#68706b;font-size:30rpx;line-height:1.8}.detail-section{margin-top:28rpx;padding:22rpx 0;border-top:1rpx solid #dfe2dd;border-bottom:1rpx solid #dfe2dd}.section-head{display:flex;align-items:center}.section-head text{font-size:34rpx;font-weight:700}.info-row{min-height:86rpx;display:flex;justify-content:space-between;align-items:center;border-bottom:1rpx solid #e5e7e2}.info-row:last-child{border-bottom:0}.info-row text{color:#7f8681;font-size:28rpx}.info-row strong{font-size:29rpx;font-weight:500}.detail-actions{margin-top:24rpx;display:flex;gap:12rpx}.detail-actions .primary-button,.quiet-button{flex:1;height:88rpx;margin:0;border-radius:9rpx;line-height:88rpx;font-size:29rpx}.quiet-button{border:1rpx solid #dfe2dd;background:#fff;color:#52605a}.loading-state{padding:180rpx 28rpx;text-align:center;color:#8b918d}.loading-state button{display:block;height:76rpx;margin:20rpx auto 0;padding:0 24rpx;border-radius:9rpx;background:#315c4d;color:#fff;line-height:76rpx;font-size:27rpx}
.back-button{position:fixed;z-index:5;top:20rpx;left:24rpx;width:58rpx;height:58rpx;margin:0;padding:0;border:0;border-radius:50%;background:rgba(255,255,255,.9);color:#315c4d;line-height:54rpx;font-family:Georgia,serif;font-size:48rpx;box-shadow:0 4rpx 14rpx rgba(35,43,38,.08)}
</style>
