<template>
  <button class="back-button" aria-label="Back" @tap="goBack">‹</button>
  <view class="event-detail-page">
    <view v-if="event" class="event-content">
      <view class="detail-head"><view><text class="eyebrow">重要日子</text><text class="page-title">重要日子</text><text class="detail-subtitle">{{ relationship?.name || '关系' }} · {{ formatDate(event.eventDate) }}</text></view><button class="edit-button" @tap="edit">编辑</button></view>
      <view class="event-hero"><text class="hero-eyebrow">{{ countdown }}</text><text class="hero-title">{{ event.title }}</text><view class="hero-date"><strong>{{ dateNumber }}</strong><view><text>{{ weekday }}</text><text>{{ event.repeatType || '不重复' }}</text></view></view><text class="hero-meta">{{ remindText }} · 仅自己可见</text></view>
      <view class="detail-section"><view class="section-head"><text>准备建议</text></view><button class="suggestion-row suggestion-action" @tap="goAI('blessing')"><view class="suggestion-icon coral">祝</view><view><text>写一段祝福</text><text>用一句真诚的话表达心意</text></view><text>›</text></button><button class="suggestion-row suggestion-action" @tap="goAI('gift')"><view class="suggestion-icon gold">礼</view><view><text>挑选一份礼物</text><text>根据对象和预算获取建议</text></view><text>›</text></button><view class="suggestion-row suggestion-note"><view class="suggestion-icon green">见</view><view><text>安排见面或通话</text><text>给这一天留出完整的时间</text></view><text class="suggestion-status">建议</text></view></view>
      <view class="detail-section"><view class="section-head"><text>事件信息</text></view><view class="info-row"><text>关联关系</text><strong>{{ relationship?.name || '关系' }}</strong></view><view class="info-row"><text>重复规则</text><strong>{{ event.repeatType || '不重复' }}</strong></view><view class="info-row"><text>提醒时间</text><strong>{{ remindText }}</strong></view></view>
      <button class="delete-button" @tap="remove">删除这个日子</button>
    </view>
    <view v-else class="loading-state"><text>{{ error || '正在加载事件…' }}</text><button v-if="error" @tap="load">重试</button></view>
  </view>
</template>

<script setup>
import { computed, ref } from 'vue';
import { onLoad, onShow } from '@dcloudio/uni-app';
import { eventApi } from '@/api/event.js';
import { relationshipApi } from '@/api/relationship.js';
import { store } from '@/store/index.js';

const eventId = ref(0); const relationshipId = ref(0); const event = ref(null); const relationship = ref(null); const error = ref('');
onLoad((options) => { eventId.value = Number(options?.id) || 0; }); onShow(() => { if (!store.isLogin) return uni.reLaunch({ url: '/pages/login/login' }); if (eventId.value) load(); });
const load = async () => { error.value = ''; try { event.value = await eventApi.detail(eventId.value); relationshipId.value = event.value.relationshipId; relationship.value = await relationshipApi.detail(relationshipId.value); } catch (requestError) { error.value = requestError?.message || '事件加载失败'; } };
const dateValue = computed(() => event.value ? new Date(event.value.eventDate) : new Date()); const dateNumber = computed(() => `${String(dateValue.value.getMonth() + 1).padStart(2, '0')}.${String(dateValue.value.getDate()).padStart(2, '0')}`); const formatDate = (value) => { const date = new Date(value); return `${date.getFullYear()}年${date.getMonth() + 1}月${date.getDate()}日`; }; const weekday = computed(() => ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'][dateValue.value.getDay()]); const countdown = computed(() => { const today = new Date(); today.setHours(0, 0, 0, 0); const target = new Date(dateValue.value); target.setHours(0, 0, 0, 0); const days = Math.round((target - today) / 86400000); return days <= 0 ? '今天' : `还有 ${days} 天`; }); const remindText = computed(() => Array.isArray(event.value?.remindDays) && event.value.remindDays.length ? `提前 ${event.value.remindDays[0]} 天提醒` : '日程内提醒');
const edit = () => uni.navigateTo({ url: `/pages/event/create?id=${eventId.value}&relationshipId=${relationshipId.value}` }); const goAI = (type) => uni.navigateTo({ url: `/pages/ai/${type}?relationshipId=${relationshipId.value}` }); const remove = () => uni.showModal({ title: '删除重要日子', content: '删除后将无法恢复，确认继续吗？', confirmColor: '#b64f43', success: async ({ confirm }) => { if (!confirm) return; await eventApi.remove(eventId.value); uni.showToast({ title: '已删除', icon: 'success' }); setTimeout(() => uni.navigateBack(), 500); } });
const goBack = () => { const pages = getCurrentPages(); if (pages.length > 1) return uni.navigateBack(); uni.reLaunch({ url: '/pages/index/index' }); };
</script>

<style scoped>
.event-detail-page{min-height:100vh;padding:28rpx 28rpx 50rpx;background:#f7f6f1}.detail-head{display:flex;align-items:flex-start;justify-content:space-between}.detail-head>view{display:flex;flex-direction:column}.eyebrow{color:#9a6d54;font-size:24rpx;font-weight:700;letter-spacing:0}.detail-subtitle{margin-top:8rpx;color:#858c87;font-size:28rpx}.edit-button{height:64rpx;margin:12rpx 0 0 12rpx;padding:0 18rpx;border:1rpx solid #dfe2dd;border-radius:9rpx;background:#fff;color:#315c4d;line-height:62rpx;font-size:27rpx}.event-hero{margin-top:26rpx;padding:26rpx;border-radius:12rpx;background:#176b5b;color:#fff;box-shadow:0 12rpx 26rpx rgba(23,107,91,.16)}.hero-eyebrow{color:#bfe0d3;font-size:27rpx}.hero-title{display:block;margin-top:10rpx;font-size:40rpx;font-weight:700}.hero-date{margin-top:28rpx;display:flex;align-items:center;gap:16rpx}.hero-date strong{font-family:Georgia,serif;font-size:64rpx;font-weight:500}.hero-date view{display:flex;flex-direction:column;gap:4rpx;color:#c9e1d7;font-size:25rpx}.hero-meta{display:block;margin-top:22rpx;color:#c9e1d7;font-size:26rpx}.detail-section{margin-top:24rpx;padding:22rpx 0;border-top:1rpx solid #dfe2dd;border-bottom:1rpx solid #dfe2dd}.section-head{display:flex;align-items:center;justify-content:space-between}.section-head>text:first-child{font-size:34rpx;font-weight:700}.suggestion-row,.info-row{min-height:100rpx;display:flex;align-items:center;border-bottom:1rpx solid #e5e7e2}.suggestion-action{width:100%;margin:0;padding:0;border:0;border-radius:0;background:transparent;color:#202522;line-height:1.5;text-align:left}.suggestion-row:last-child,.info-row:last-child{border-bottom:0}.suggestion-icon{width:60rpx;height:60rpx;margin-right:14rpx;border-radius:10rpx;display:flex;align-items:center;justify-content:center;font-size:27rpx;font-weight:700}.suggestion-icon.coral{background:#f7dfd6;color:#915041}.suggestion-icon.gold{background:#f1e7d4;color:#7a612d}.suggestion-icon.green{background:#dcebe3;color:#315c4d}.suggestion-row>view:nth-child(2){flex:1;display:flex;flex-direction:column}.suggestion-row>view:nth-child(2) text:first-child{font-size:30rpx;font-weight:650}.suggestion-row>view:nth-child(2) text:last-child{margin-top:5rpx;color:#8b918d;font-size:26rpx}.suggestion-row>text:last-child{color:#9ca29e;font-size:34rpx}.suggestion-note{color:#68706b}.suggestion-row>text.suggestion-status:last-child{font-size:24rpx}.info-row{justify-content:space-between;min-height:86rpx}.info-row text{color:#7f8681;font-size:28rpx}.info-row strong{font-size:29rpx;font-weight:500}.delete-button{height:88rpx;margin-top:30rpx;border:1rpx solid #e1c4bd;border-radius:9rpx;background:#fff;color:#b64f43;line-height:86rpx;font-size:28rpx}.loading-state{padding:180rpx 28rpx;text-align:center;color:#8b918d}.loading-state button{display:block;height:76rpx;margin:20rpx auto 0;padding:0 24rpx;border-radius:8rpx;background:#315c4d;color:#fff;line-height:76rpx;font-size:27rpx}
.back-button{position:fixed;z-index:5;top:20rpx;left:24rpx;width:58rpx;height:58rpx;margin:0;padding:0;border:0;border-radius:50%;background:rgba(255,255,255,.9);color:#315c4d;line-height:54rpx;font-family:Georgia,serif;font-size:48rpx;box-shadow:0 4rpx 14rpx rgba(35,43,38,.08)}
</style>
