<template>
  <view class="workflow-page">
    <view class="field-card">
      <text class="field-label">祝福对象</text>
      <picker :range="people" range-key="name" @change="personIndex=$event.detail.value">
        <view class="person-row"><view class="avatar">{{ selectedPerson.name.slice(0,1) }}</view><view><text class="person-name">{{ selectedPerson.name }}</text><text class="person-meta">{{ selectedPerson.type }} · {{ selectedPerson.birthday ? formatDate(selectedPerson.birthday) : '重要的人' }}</text></view><text class="arrow">›</text></view>
      </picker>
    </view>
    <view class="field-card"><text class="field-label">祝福场景</text><picker :range="scenes" :value="sceneIndex" @change="sceneIndex=$event.detail.value"><view class="picker-row"><text>{{ scenes[sceneIndex] }}</text><text>⌄</text></view></picker></view>
    <view class="field-card"><text class="field-label">祝福风格</text><view class="style-pills"><view v-for="item in styles" :key="item" :class="{active:style===item}" @tap="style=item">{{item}}</view></view></view>
    <button class="primary-button generate" :loading="loading" @tap="generate">生成祝福语</button>
    <view v-if="result" class="result-card"><text class="field-label">生成结果</text><text class="result-text">{{result}}</text><view class="result-actions"><button @tap="copy">□ 复制</button><button @tap="generate">↻ 换一条</button></view></view>
  </view>
</template>
<script setup>
import { computed, ref } from 'vue';import { onLoad } from '@dcloudio/uni-app';import { store } from '@/store/index.js';import { relationshipApi } from '@/api/relationship.js';import { aiApi } from '@/api/ai.js';import{trackEvent}from'@/utils/analytics.js';
const people=ref([{name:'重要的人',type:'关系',birthday:''}]),personIndex=ref(0),sceneIndex=ref(0),style=ref('温暖感人'),loading=ref(false),result=ref('');const scenes=['生日祝福','纪念日祝福','节日祝福','日常关怀'];const styles=['温暖感人','幽默风趣','简洁大方','文艺浪漫'];const selectedPerson=computed(()=>people.value[Number(personIndex.value)]||people.value[0]);
onLoad(async(options)=>{if(!store.isLogin)return uni.reLaunch({url:'/pages/login/login'});try{const list=await relationshipApi.list(store.userId);if(list?.length){people.value=list;const index=list.findIndex(item=>item.id===Number(options.relationshipId));if(index>=0)personIndex.value=index;}}catch{}});const formatDate=v=>{const d=new Date(v);return `${d.getMonth()+1}月${d.getDate()}日`;};const generate=async()=>{loading.value=true;try{const prompt=`请为${selectedPerson.value.type}${selectedPerson.value.name}写一段${scenes[sceneIndex.value]}，风格为${style.value}，内容真诚自然。`;const data=await aiApi.generate({userId:store.userId,type:'blessing',relationshipId:selectedPerson.value.id,scene:scenes[sceneIndex.value],style:style.value,prompt});result.value=data.result;trackEvent('ai_generated',{type:'blessing',hasRelationship:Boolean(selectedPerson.value.id)});}finally{loading.value=false;}};const copy=()=>uni.setClipboardData({data:result.value});
</script>
<style scoped>
.workflow-page{min-height:100vh;padding:24rpx 28rpx 50rpx;background:#f7f7f5}.field-card,.result-card{margin-bottom:18rpx;padding:22rpx 24rpx;border-radius:12rpx;background:#fff;border:1rpx solid #dedfd9}.field-label{display:block;margin-bottom:16rpx;font-size:32rpx;font-weight:600;color:#303833}.person-row,.picker-row{display:flex;align-items:center;min-height:88rpx}.avatar{width:76rpx;height:76rpx;margin-right:14rpx;border-radius:50%;background:#ffe0d4;color:#785345;display:flex;align-items:center;justify-content:center;font-weight:700}.person-row>view:nth-child(2){flex:1;display:flex;flex-direction:column}.person-name{font-size:32rpx;font-weight:600}.person-meta{margin-top:5rpx;color:#8b918d;font-size:26rpx}.arrow{margin-left:auto;color:#9ca29e;font-size:34rpx}.picker-row{justify-content:space-between;font-size:32rpx}.style-pills{display:flex;flex-wrap:wrap;gap:12rpx}.style-pills view{min-height:72rpx;display:flex;align-items:center;padding:10rpx 20rpx;border-radius:12rpx;background:#edf0ec;color:#737a75;font-size:28rpx}.style-pills view.active{min-height:72rpx;display:flex;align-items:center;background:#e4ece7;color:#315c4d}.generate{margin-top:28rpx}.result-card{margin-top:28rpx}.result-text{display:block;min-height:140rpx;padding:18rpx;border-radius:12rpx;background:#f7f7f5;color:#303833;font-size:32rpx;line-height:1.8;white-space:pre-wrap}.result-actions{display:flex;justify-content:flex-end;gap:12rpx;margin-top:14rpx}.result-actions button{margin:0;padding:0 20rpx;height:88rpx;line-height:88rpx;border-radius:10rpx;background:#fff;color:#315c4d;border:1rpx solid #dfe2dd;font-size:28rpx}
</style>
